### ISSUE TITLE
error getting file assets.auth0.com file - 

### ISSUE THREAD

**Issue by nigel-dewar** [diegose/MBS.Auth0#2]
Hi there, installed your module,

configured all correctly, and added widget to orchard page,

it shows up, and when i hit the sign in button, nothing happens. When I check the chrome console I get 

Failed to load resource: the server responded with a status of 403 (Forbidden)  "On this file here"
https://s3.amazonaws.com/assets.auth0.com/client/CJT0MIvy45N82uxCWgBgsLsKYU5tkMbR.js

Please advise

cheers

**Comment by diegose** [comment]
I haven't touched or used this project in years. I'm afraid I can't help.

**Comment by nigel-dewar** [comment]
No probs mate. I understand all good.

Sent from Samsung Mobile

-------- Original message --------
From: diegose
Date:16/11/2016 03:50 (GMT+10:00)
To: "diegose/MBS.Auth0"
Cc: nigel-dewar , Author
Subject: Re: [diegose/MBS.Auth0] error getting file assets.auth0.com file - (#2)

I haven't touched or used this project in years. I'm afraid I can't help.

##
